FROM ruby:%%VERSION%%-alpine

RUN apk add --no-cache nodejs mariadb-dev mariadb-client dcron postgresql-client postgresql-dev git build-base \
      libxml2 libxml2-dev libxslt libxslt-dev tzdata curl coreutils
RUN bundle config build.nokogiri --use-system-libraries
RUN npm install -g yarn

